services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:sukanya@postgres:5432/stackbox
      - AZURE_STORAGE_CONN_STR=DefaultEndpointsProtocol=https;AccountName=stackbox;AccountKey=mkD+YsGFkRQIMz1Irm3qZGU96/ToAOqPlV3KxX/vIY2PcS7uzvO829IcEBvGBfir7dXn/+KKcMEJ+AStcc0wPg==;EndpointSuffix=core.windows.net
      - AZURE_CONTAINER_NAME=stackbox
      - AZURE_ACCOUNT_NAME=stackbox
      - AZURE_ACCOUNT_KEY=mkD+YsGFkRQIMz1Irm3qZGU96/ToAOqPlV3KxX/vIY2PcS7uzvO829IcEBvGBfir7dXn/+KKcMEJ+AStcc0wPg==
    depends_on:
      - postgres
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    restart: always

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sukanya
      - POSTGRES_DB=stackbox
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
