name: Deploy Ec2 Instance

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  deploy-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
       
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      

   